all: exercise1 exercise2

exercise1: exercise1.c
	gcc -Wall -g -fno-stack-protector -o exercise1 exercise1.c

exercise2: exercise2.c
	gcc -Wall -g -o exercise2 exercise2.c

clean:
	rm exercise1 exercise2
