all: exercise1 exercise2 exercise3

exercise1: exercise1.c
	gcc -Wall -g -O3 -o exercise1 exercise1.c

exercise2: exercise2.c
	gcc -Wall -g -o exercise2 exercise2.c

exercise3: exercise3.c test_exercise3.c
	gcc -Wall -g -O3 -o exercise3 exercise3.c test_exercise3.c
